[release] Adds GridView constructor taking just a grid as exspected by GridDefaultImplementation see FS1390.
For some time the checks of GeometryGrid in dune-grid failed with an error along
the lines:

In file included from test-geogrid.cc:4:
In file included from ../../../config.h:354:
In file included from ../../../dune/grid/yaspgrid.hh:18:
../../../dune/grid/common/grid.hh:1058:19: error: no matching conversion for
functional-style cast from 'const GridImp' (aka 'const
GeometryGrid<Dune::YaspGrid<2>, Dune::IdenticalCoordFunction<double, 2>,
std::allocator<void>
') to 'ViewImp' (aka 'GridView<HostGridView,
Dune::IdenticalCoordFunction<double, 2>, std::allocator<void>,
(Dune::PartitionIteratorType)4U>')
return View(ViewImp(asImp()));
^~~~~~~~~~~~~~~

Basically the GridDefaultImplementation exspects each GridView to have constructor
with the GridImplementation as the only argument. This was missing in GeometryGrid.
This patch simply adds one and all tests succeed again.